### ISSUE TITLE
implement L10N in flutter

### ISSUE THREAD

**Issue by GabrielAderaldo** [shrimp-dev/RoleManager-flutter-frontend#6]
**Task**

- [ ]  Criar a branch
- [ ]  Ler a documentação 
- [ ]  Instalar o pub spec
- [ ]  implementar os protocolos
- [ ]  Descobrir por que não tá gerando os arquivos
- [ ] Mudar a branch antes de voltar
- [ ]  verficar se está tudo certo
