### ISSUE TITLE
create modal login

### ISSUE THREAD

**Issue by GabrielAderaldo** [shrimp-dev/RoleManager-flutter-frontend#9]
### Criar a modal convidar amigos.
**Criterio de aceite**
_O usuario clicar no botão de convidar amigos e depois abrir uma tela de modal, onde assim que ela for apresentada para o usuario, ele possa colocar um link ou um codigo hash. Se for aceito sendo direcionado para outra tela._

**Tasks:**

- [x] Criar uma branch propia 
- [x] Criar o layout da tela 
- [x] Fazer as validações basicas
